name: Create Release on Push to Master

on:
  push:
    branches:
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Latest Tag
        id: get_tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Bump Version and Create Tag
        id: tag
        run: |
          OLD_TAG=${{ steps.get_tag.outputs.latest_tag }}
          echo "Previous tag: $OLD_TAG"
          VERSION=$(echo $OLD_TAG | sed 's/v//' | awk -F. '{printf("v%d.%d.%d", $1, $2, $3+1)}')
          echo "New version: $VERSION"
          git tag $VERSION
          git push origin $VERSION
          echo "tag_name=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: Release ${{ steps.tag.outputs.tag_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
